version: "3.8"

services:

  phpapache:
    container_name: weather-task
    build:
      context : .
      dockerfile: docker/docker-files/apache.dockerfile
      args:
        user: test-user
        uid: 1000
    volumes:
      - ./:/var/www/html
      - ./docker/apacheconf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    ports:
      - "8081:80"

